language: node_js
node_js:
- '8'
- '10'
- '12'

deploy:
  provider: npm
  email: mail@anderl-bauer.de
  api_key:
    secure: fHQJfv59fMrkabHMvq5zXdBlRclNef21MKnET7+vStrOUq8D9bbOWChKN+NEqiFNj/PxPMdOwTTCckAppSyYU7E/WQXwDEQyol4hAvMlgWVjKw/rGprxuR7p3cafnyLz8T9OOujo89VqlLY9Ljebk5jhcYRKF10K1Ed09atfWtUfOzNoAxV7qj8YTydxNQru9/sX8RunKVr9/atMT83YSd3CHMWyubAKxU3UKHhtjMYXSHtcz4021eqit9wyaIV37kDBYidscOjrlDyN1erGY/lpyO59MFvOCd8dWLy248YIv1TmhwednTaGvpCcNw3kQ0xochKkSODT+CkgQV4rL0gOKMX4yUATELsKggt6KYPIsL/r8JJaHxscnscPcpU6Idq6XBhPL4M4UAFMP/qgMuFcIoN65tOwqTyL/lJRxK1RWLsy6ktpQtNDvj95XOLUjoTdGJmHow5aGRhJn9bjh3TNOymGEO+aSKN2aUooMFVfg/h4pyE0r9GBOQL4mTswxZMG1U2/3nGagPAA9pyhWiXFmba/nloVZZLS+g/Di+2fRBO9msDCwYiycKLlroNJMx+KXl7ulWEVJHXva/1W/wrJyiWbZyRrc21vI4h1HDdh+g3S/X9r09N+fD2W4gnAgQIN4SeJoFapKwmWVdKPa+4Bd0gsDVaHujkfuF4aUlU=
  on:
    tags: true
    repo: Supereg/homebridge-http-base
  skip_cleanup: true
