name: Node-CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
        env:
          CI: true
      - name: npm build
        run: npm run build --if-present
        env:
          CI: true
      - name: npm test
        run: npm test
        env:
          CI: true

  publish-npm:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com/
          scope: '@Supereg'
      - run: npm ci
      - run: echo registry=https://npm.pkg.github.com/Supereg >> .npmrc # Values above don't seem to be honored
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
