name: Node-CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
        env:
          CI: true
      - name: npm build
        run: npm run build --if-present
        env:
          CI: true
      - name: npm test
        run: npm test
        env:
          CI: true

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: npm publish (if version has been updated)
        uses: houtianze/npm-publish-action@master
        with:
          commit_pattern: "^(\\S+)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.npm_token }}
